### ISSUE TITLE
Crear Wiki con ejemplos de uso

### ISSUE THREAD

**Issue by pablo-moreno** [pablo-moreno/python-aemet#12]
Estaría bien crear una wiki con casos de uso generales dado que hay mucha gente utilizando esta librería ya.

**Comment by jmrr** [comment]
Hola, @pablo-moreno, estoy utilizando vuestra librería (gracias!), y no me importaría documentar los casos de uso que estoy usando en la wiki. A la vez, puedo crear issues allí donde me he encontrado con algún problema y crear PRs para arreglarlos. 

¿Dónde preferís que documente los casos de uso, en la wiki, README.md, otro sitio?

**Comment by pablo-moreno** [comment]
Hola @jmrr ! muchas gracias por ofrecerte a documentar. Por el momento podemos crear una carpeta de use cases y dentro uno o varios archivos en Markdown si te parece.
