### ISSUE TITLE
Desaparición Opción descargar climatologias diarias 

### ISSUE THREAD

**Issue by dargueso** [pablo-moreno/python-aemet#17]
Parece que ha desaparecido en la última versión la función para descargar valores climatológicos diarios
get_valores_climatologicos_diarios

**Comment by pablo-moreno** [comment]
Hola @dargueso , ¿en qué versión estaba esa función?

**Comment by dargueso** [comment]
Hola @pablo-moreno, creo que en la última (0.2.4) estaba. Por lo menos, yo no he usado ninguna previa a Febrero de 2020, y parece que esa es la vigente en esa fecha. Yo la he incorporado a la versión 0.3.0, si quieres puedo hacer un pull-request para añadirla. Sólo hay un par de archivos modificados (models.py y constants.py). Ya lo he probado en varias estaciones y funciona como antes.
Un saludo y gracias

**Comment by pablo-moreno** [comment]
Pues adelante @dargueso !
