### ISSUE TITLE
Missing data in class Observación

### ISSUE THREAD

**Issue by pherodeon** [pablo-moreno/python-aemet#24]
{
  "idema" : "9073X",
  "lon" : -2.359745,
  "fint" : "2020-12-03T10:00:00",
  "prec" : 0.0,
  "alt" : 660.0,
  "vmax" : 1.3,
  "vv" : 0.9,
  "dv" : 144.0,
  "lat" : 42.82983,
  "dmax" : 135.0,
  "ubi" : "OPAKUA",
  **"hr" : 93.0,
  "tamin" : 5.0,
  "ta" : 5.5,
  "tamax" : 5.5**
}

**Comment by pablo-moreno** [comment]
Version 0.3.4 already in Pypi: 

https://pypi.org/project/python-aemet/
